
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MywsService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/myws?wsdl")
public class MywsService
    extends Service
{

    private final static URL MYWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYWSSERVICE_EXCEPTION;
    private final static QName MYWSSERVICE_QNAME = new QName("http://server/", "MywsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/myws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYWSSERVICE_WSDL_LOCATION = url;
        MYWSSERVICE_EXCEPTION = e;
    }

    public MywsService() {
        super(__getWsdlLocation(), MYWSSERVICE_QNAME);
    }

    public MywsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYWSSERVICE_QNAME, features);
    }

    public MywsService(URL wsdlLocation) {
        super(wsdlLocation, MYWSSERVICE_QNAME);
    }

    public MywsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYWSSERVICE_QNAME, features);
    }

    public MywsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MywsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Myws
     */
    @WebEndpoint(name = "MywsPort")
    public Myws getMywsPort() {
        return super.getPort(new QName("http://server/", "MywsPort"), Myws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Myws
     */
    @WebEndpoint(name = "MywsPort")
    public Myws getMywsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "MywsPort"), Myws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYWSSERVICE_EXCEPTION!= null) {
            throw MYWSSERVICE_EXCEPTION;
        }
        return MYWSSERVICE_WSDL_LOCATION;
    }

}
