
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Myws", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Myws {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "stopWS", targetNamespace = "http://server/", className = "client.StopWS")
    @ResponseWrapper(localName = "stopWSResponse", targetNamespace = "http://server/", className = "client.StopWSResponse")
    @Action(input = "http://server/Myws/stopWSRequest", output = "http://server/Myws/stopWSResponse")
    public void stopWS();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doSomething", targetNamespace = "http://server/", className = "client.DoSomething")
    @ResponseWrapper(localName = "doSomethingResponse", targetNamespace = "http://server/", className = "client.DoSomethingResponse")
    @Action(input = "http://server/Myws/doSomethingRequest", output = "http://server/Myws/doSomethingResponse")
    public String doSomething();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayH", targetNamespace = "http://server/", className = "client.SayH")
    @ResponseWrapper(localName = "sayHResponse", targetNamespace = "http://server/", className = "client.SayHResponse")
    @Action(input = "http://server/Myws/sayHRequest", output = "http://server/Myws/sayHResponse")
    public String sayH(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
